# =============================================================================
# roles/system_tuning/defaults/main.yml 
# =============================================================================
---
# Порог "слабой VM"
system_min_ram_mb: 2048

# Swap
system_swap_size: 1024
system_swap_file: /swapfile

# Ограничение параллелизма
system_serial: 1
