# =============================================================================
# host_vars/lighthouse.yml – Хост-специфичные переменные для Lighthouse
# =============================================================================

lighthouse_host_ip: "51.250.1.216"
