# =============================================================================
# host_vars/vector-01.yml – Хост-специфичные переменные для Vector
# =============================================================================

vector_host_ip: "51.250.70.164"
