# =============================================================================
# host_vars/vector.yml – Хост-специфичные переменные для Vector
# =============================================================================

vector_host_ip: "46.21.246.91"
